### PR TITLE
Add Proxysql Clustering with Core and Satellite Nodes

### PR DESCRIPTION
**Pull request by reixd**
this PR adds capabilities to enable ProxySQL Clustering, if needed.

* Core Nodes: in charge on syncing the configuration between each other. Any change in the config inside this nodes will be distributed among the whole cluster (Core+Satellites)
* Core Nodes run as a `StatefullSet` of >=3 nodes. 
* Additional Core nodes can be added by simple changes in the helmfile config
* Satellite Nodes: are the workhorses and run as a DaemonSet on each Node. Can be reached by any app by calling `proxysql:6033`
* By setting `topologyKeys` in the Services a connecting client will prefer a local node, a zonal node, then regional endpoints but falls back to cluster wide endpoints, improving the concept of a localhost listening proxysql daemon  

WARNING: currently is the proxysql.db NOT PERSISTENT! Thus on each boot this DB will be re-created based on the templated proxysql.cfg fil created by helm. Hence persistent configuration MUST BE SAVED in the helm chart/helmfile!

Changes:
* Move config file to own file with templates under `files/proxysql.cfg`
* Template this file inside a new ConfigMap
* Move admin_credentials and password stuff to own file
* Store credentials in a Secret
* Mount ConfigMap and Secret data accordingly
* Add ProxySQL Clustering capabilities:
  * Add DaemonSet for Satellite Nodes
  * Add StatefullSet for Code Nodes
  * Disable Deployment  kind when clustering
  * Enable 6032 admin port
  * Add headless service for Core nodes
  * Add port for Web UI. Currently not coped to any service
  * Add annotation to update/restart resources on any config/password change
* Update values.yaml accordingly

Refs:
* https://www.percona.com/blog/2019/08/14/how-to-manage-proxysql-cluster-with-core-and-satellite-nodes/
* https://www.percona.com/blog/2018/06/11/proxysql-experimental-feature-native-clustering/
* https://mydbops.wordpress.com/2020/02/27/proxysql-series-proxysql-native-cluster/

### CODE REVIEW

**Comment by dennybaa** [comment]
Thanks @reixd for this great contribution. Please fix the version  ✖︎ proxysql => (version: "0.1.5", path: "dysnix/proxysql") > Chart version not ok. Needs a version bump!

**Comment by reixd** [comment]
Wilco!

**Comment by reixd** [comment]
> Thanks @reixd for this great contribution. Please fix the version ✖︎ proxysql => (version: "0.1.5", path: "dysnix/proxysql") > Chart version not ok. Needs a version bump!

Done, please start the tests again

**Comment by reixd** [comment]
@dennybaa added a new job resource to update the cluster config and display the current table hashes.
This is a recommendation by SysOwn to guarantee a synced cluster.
Also bumped the chart

**Comment by reixd** [comment]
@dennybaa lint errors fixed.

**Comment by dennybaa** [comment]
@reixd Hey. Thank you :100: !

**Pull request merged**
