### PR TITLE
[nifi-registry] Allow images to be overridable.

### PR DESCRIPTION
**Pull request by kfox1111**

### CODE REVIEW

**Comment by kfox1111** [comment]
ping

**Comment by dennybaa** [comment]
howdy @kfox1111 Thanks for the contribution. This is a duplicate of #32

**Comment by dennybaa** [comment]
Could you please change to `{{ .Values.initContainers.git.image }}` keys style, it seems more obvious?

**Comment by dennybaa** [comment]
resolved in #41

**Pull request closed without merging**
