### PR TITLE
Upgrading nifi-registry ingress to support k8s >=1.19

### PR DESCRIPTION
**Pull request by r65535**
I'm trying to deploy nifi-registry on k8s `v1.24.2` but the ingress templates do not currently support `networking.k8s.io/v1`

I've added this functionality, basing it on the existing template in `charts/dysnix/dshackle/templates/ingress.yaml`

### CODE REVIEW

**Comment by r65535** [comment]
@dennybaa / @daniel-yavorovich / @voron / @killmeplz
Sorry for the mass-ping! Would one of you be able to take a look at this PR? :)

**Comment by voron** [comment]
@r65535 Thank you for the attention, and sorry for the delay! I'll merge this PR.

**Comment by voron** [comment]
>Is this something I can fix on a branch, or does it require contrib rights to this repo?

Each release requires version bump inside `Chart.yaml`

**Comment by r65535** [comment]
> > Is this something I can fix on a branch, or does it require contrib rights to this repo?
> 
> Each release requires version bump inside `Chart.yaml`

Ahh, apologies - I know for next time!
I've raised a follow up PR [here](https://github.com/dysnix/charts/pull/207) to release the nifi-registry charts

**Comment by voron** [comment]
Pipeline seems to be fine after the patch, thank you!

**Pull request merged**
