### PR TITLE
add git flowProvider and ssh support

### PR DESCRIPTION
**Pull request by makeacode**
Added ability to use gitFlowProvider

create secret with private key for git repo:
```
kubectl -n nifi-registry create secret generic nifi-registry-git-deploy --from-file=./identity
```
example values.yaml:
```yaml
flowProvider:
  git:
    enabled: true
    url: <git-repo-url>

ssh: 
  known_hosts: <known host identity>         
  config: |
    Host <git repo server>
    IdentityFile /ssh/id_rsa

```

### CODE REVIEW

**Comment by makeacode** [comment]
Well....I tried working through the linting errors but I'm stuck at this point.

**Comment by dennybaa** [comment]
Hey  @makeacode , try merging the master, I believe maintainer should have a email https://github.com/dysnix/charts/commit/1a441cbdf11b5cd3e818f841a3647707e7280d1e

Thanks

**Comment by dennybaa** [comment]
https://github.com/dysnix/charts/commit/1a441cbdf11b5cd3e818f841a3647707e7280d1e

**Comment by makeacode** [comment]
if you can get your master brank to pass i'll merge it in

**Comment by makeacode** [comment]
@dennybaa any luck?

**Comment by dennybaa** [comment]
@makeacode  I can not fix on your PR branch... The linter complains because of the space in in the maintainer name.

**Comment by dennybaa** [comment]
For me looks sane @makeacode . @daniel-yavorovich plz have a look and give it a go.

**Comment by dennybaa** [comment]
@makeacode is there any place where git is used apart from the init container?

**Comment by dennybaa** [comment]
I believe on a container start any .ssh directory such as /home/nifi/.ssh should be empty, so know_hosts part doesn't have sense in fact.

**Comment by dennybaa** [comment]
Well yes, maybe some interactive action. Anyways easier to add a config

```
Host *
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null 
```

**Comment by makeacode** [comment]
the point of the PR is to be able to use nifi-registry's ability to store flow files in a git repo.  unfortunatley the version of nifi-registry currently available in a docker image doesn't support cloning that repo initially which is why I created the init container.  for my security purposes, I'd rather not blanket accept the ssh key given by the server but supply the key I expect.  the purpose of adding the known_hosts file is to avoid the interactive "do you accept this host's key" prompt.

**Comment by makeacode** [comment]
well i guess i should have checked dockerhub before commenting.  apparently the 0.7.0 image was posted August 20th which mitigates the init container's purpose.  the additional environment variables to supply the git repo parameters are still needed though.  I will rework with the new image.

**Comment by makeacode** [comment]
@dennybaa @daniel-yavorovich any chance I can get this merged

**Comment by dennybaa** [comment]
@makeacode thank you!

**Comment by makeacode** [comment]
I noticed the new 0.2.0 version of the chart is not available through the index.yaml of the helm repo.  Some investigation shows the release has failed for some reason....

https://github.com/dysnix/charts/runs/1491480553?check_suite_focus=true

**Comment by dennybaa** [comment]
@makeacode i've bumped version

**Pull request merged**
