### PR TITLE
NiFi Registry JGit SSH client fails if /home/nifi/.ssh is not writable

### PR DESCRIPTION
**Pull request by wknickless**
If /home/nifi/.ssh is not writable, JGit can't create a known_hosts.lock file and throws an exception.  This makes it impossible for NiFi Registry to check in a commit to a Git repository via SSH, and leaves NiFi in a state where there is no checked-in revision of a process group.

Also, extraEnvs was broken because indent was being used instead of nindent.

Finally, the values.yaml comments show creating an SSH private key named identity, but the chart actually expects the private key to be named id_rsa.

### CODE REVIEW

**Comment by erorci** [comment]
@wknickless I having some issues to make my nifi-registry work, I will test your changes.

**Comment by dennybaa** [comment]
@wknickless Thanks, great :+1: , could you bump version too or should I?

**Comment by wknickless** [comment]
Done -- happy to help!

**Comment by dennybaa** [comment]
@wknickless Hey, I can go and force merge this PR. Have you tested the changes? I'm not very familiar with this chart, but as I see the default settings can be validated, i.e. deployment fails (evidently due to the lack of postgres). So WDYT?

**Comment by wknickless** [comment]
Hi @dennybaa it looks like commit d910455572fef84dd48fd7ef7141010b32255f19 sets flowProvider.postgres.enabled to true, but I don't see anything in the statefulset that spins up a postgres container to accept connections.  The lint-test failed for that one because the chart version hadn't been bumped.  Commit 979bd830393ce2010a6adcbb7e32db9ad83ed760 bumps the chart version but I don't see any lint-test results.

Would you like me to send you a separate one-liner PR that disables postgres in values.yaml by default?  I bet lint-test would then pass after you apply it, and then you could test this PR to confirm it passes against the updated master baseline.

Internally we've been applying these patches directly as part of our GitLab CI/CD pipeline that copies the chart into an internal registry:

```
curl --location https://github.com/dysnix/charts/releases/download/nifi-registry-0.3.5/nifi-registry-0.3.5.tgz | tar xvzf -
curl --location https://github.com/wknickless/dysnix-charts/commit/888ae5e67a92d555afd636bcca065ec20ef52016.patch | patch -p2
curl --location https://github.com/wknickless/dysnix-charts/commit/133a591ceb5687d0ebbaac6cad09beacd20b5dfb.patch | patch -p2
```
...and they've been running happily for a couple of weeks, so I'm pretty confident in them.

Let me know how you'd like to proceed.

**Comment by dennybaa** [comment]
@wknickless Please set it to `false`, doesn't make sense for the defaults.

**Comment by dennybaa** [comment]
I see the following during the CI run.
```
2021-11-17 19:03:22,408 ERROR [main] o.a.n.r.db.CustomFlywayConfiguration Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

**Comment by wknickless** [comment]
@dennybaa OK I bet this will pass lint-test after you merge #120

**Comment by dennybaa** [comment]
@wknickless Thank you again.

**Pull request merged**
